### PR TITLE
Additional options

### PR DESCRIPTION
**Pull request by jhowarth**
This will allow users to specify additional options to pass to the liquibase jar.

### CODE REVIEW

**Comment by jhowarth** [comment]
@reset Can you review this?

**Comment by reset** [comment]
@jhowarth :+1: but it would be :100: if we generated the additional arguments based on attributes of the LWRP. We can think about that for a future version unless it's a simple change.

**Comment by jhowarth** [comment]
@reset the additional arguments are riot specific.  e.g. -DsomeRiotLiquidBaseProperty=somevalue

**Comment by jhowarth** [comment]
@reset Actually I could see how to make this work and be more specific.  Change incoming.

**Comment by jhowarth** [comment]
@reset How does this look?  This attribute should make a lot more sense for people who are familiar with liquibase.  It's what they refer to it as.

**Comment by reset** [comment]
@jhowarth looks good!

**Comment by jhowarth** [comment]
@reset Cool.  Can you merge and release?  If you want to give me access I can merge.  I think I should have access to release now too?

**Comment by reset** [comment]
you have access to release

**Pull request merged**
